version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Th@bata2012
      POSTGRES_DB: bnext_produtos_api
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - api_bnex_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - '15432:80'
    depends_on:
      - db
    networks:
      - api_bnex_network

  sbootapp:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: api_bnex
    restart: on-failure
    depends_on:
      - db

    ports:
      - '8080:8080'
    networks:
      - api_bnex_network
    environment:
      - "POSTGRES_HOST=db"

  app:
    build: 
      dockerfile: Dockerfile
      context: backend
    container_name: bnextapi
    depends_on:
      - sbootapp
    ports:
      - '3000:3000'
    networks:
      - api_bnex_network
    expose:
      - '3000'



networks:
  api_bnex_network:
    driver: bridge
